### ISSUE TITLE
Overriding Classess

### ISSUE THREAD

**Issue by mnazirj** [mnazirj/doctors#1]
Using the global CSS file to customize your dashboard causing conflicts with others pages. 
After taking a deep look at classes I've noticed that you are overriding **PrimeVue** Lib classes, please keep in your mind if you want to override some **Bootstrap** or **PrimeVue** Classes do it inside the style scop which make it locally to the page you overriding at.
Please don't use names that have been used by the CSS Libs to apply custom style because it cause more trouble on smaller screen
Another issue I've found that you are using the child routes wrong

@Mohammad-Alqahf

**Comment by Mohammad-Alqahf** [comment]
I got this , and I will work on it  . I grateful to review my code and give feedback to me ^_^ .
